name: Create Release & Tag
on:
  push:
    # Sequence of patterns matched against refs/tags
    paths-ignore:
      - "README.md"
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 버전 정보 추출
      run: echo "TAG=$(echo '${{ github.event.head_commit.message }}' | sed 's/[^0-9]\+[^0-9]//g')" >> $GITHUB_ENV
      id: extract_version_name       
    - name: Release 생성 
      uses: actions/create-release@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        tag_name: v${{ env.TAG }}
        release_name: v${{ env.TAG }}
        draft: false
        prerelease: false
