name: Create Release & Tag
on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - main

env:
  BUILD_CONFIGURATION: Release
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Release 생성 
      uses: actions/create-release@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with: 
        tag_name: ${{ github.ref }}
        release_name: ${{env.BUILD_CONFIGURATION}} ${{ github.ref }}
